# TODO: define production config that does not include route for sockjs-node.
# The sockjs-node route is only necessary in production so the React app will
# reload whenever there is a code change.
FROM nginx
COPY ./default.conf /etc/nginx/conf.d/default.conf
